// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Payment.Gateways;
using System.Collections.Generic;

// ReSharper disable once CheckNamespace
namespace Volo.Payment.Gateways.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IGatewayAppService), typeof(GatewayClientProxy))]
public partial class GatewayClientProxy : ClientProxyBase<IGatewayAppService>, IGatewayAppService
{
    public virtual async Task<List<GatewayDto>> GetGatewayConfigurationAsync()
    {
        return await RequestAsync<List<GatewayDto>>(nameof(GetGatewayConfigurationAsync));
    }

    public virtual async Task<List<GatewayDto>> GetSubscriptionSupportedGatewaysAsync()
    {
        return await RequestAsync<List<GatewayDto>>(nameof(GetSubscriptionSupportedGatewaysAsync));
    }
}
