// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;
using Volo.CmsKit.Admin.PageFeedbacks;

// ReSharper disable once CheckNamespace
namespace Volo.CmsKit.Admin.PageFeedbacks;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPageFeedbackAdminAppService), typeof(PageFeedbackAdminClientProxy))]
public partial class PageFeedbackAdminClientProxy : ClientProxyBase<IPageFeedbackAdminAppService>, IPageFeedbackAdminAppService
{
    public virtual async Task<PageFeedbackDto> GetAsync(Guid id)
    {
        return await RequestAsync<PageFeedbackDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<PageFeedbackDto>> GetListAsync(GetPageFeedbackListInput input)
    {
        return await RequestAsync<PagedResultDto<PageFeedbackDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetPageFeedbackListInput), input }
        });
    }

    public virtual async Task<PageFeedbackDto> UpdateAsync(Guid id, UpdatePageFeedbackDto dto)
    {
        return await RequestAsync<PageFeedbackDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(UpdatePageFeedbackDto), dto }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<List<String>> GetEntityTypesAsync()
    {
        return await RequestAsync<List<String>>(nameof(GetEntityTypesAsync));
    }

    public virtual async Task<List<PageFeedbackSettingDto>> GetSettingsAsync()
    {
        return await RequestAsync<List<PageFeedbackSettingDto>>(nameof(GetSettingsAsync));
    }

    public virtual async Task UpdateSettingsAsync(UpdatePageFeedbackSettingsInput input)
    {
        await RequestAsync(nameof(UpdateSettingsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(UpdatePageFeedbackSettingsInput), input }
        });
    }
}
