// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;
using Volo.CmsKit.Admin.PageFeedbacks;

// ReSharper disable once CheckNamespace
namespace Volo.CmsKit.Admin.PageFeedbacks;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPageFeedbackSettingsAppService), typeof(PageFeedbackSettingsClientProxy))]
public partial class PageFeedbackSettingsClientProxy : ClientProxyBase<IPageFeedbackSettingsAppService>, IPageFeedbackSettingsAppService
{
    public virtual async Task<CmsKitPageFeedbackSettingDto> GetAsync()
    {
        return await RequestAsync<CmsKitPageFeedbackSettingDto>(nameof(GetAsync));
    }

    public virtual async Task UpdateAsync(UpdateCmsKitPageFeedbackSettingDto input)
    {
        await RequestAsync(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(UpdateCmsKitPageFeedbackSettingDto), input }
        });
    }
}
