using Sapienza.Lexus.Localization;
using Volo.Abp.Authorization.Permissions;
using Volo.Abp.Localization;
using Volo.Abp.MultiTenancy;

namespace Sapienza.Lexus.Permissions
{
    public class LexusPermissionDefinitionProvider : PermissionDefinitionProvider
    {
        public override void Define(IPermissionDefinitionContext context)
        {
            var myGroup = context.AddGroup(LexusPermissions.GroupName);

            myGroup.AddPermission(LexusPermissions.Dashboard.Host, L("Permission:Dashboard"), MultiTenancySides.Host);
            myGroup.AddPermission(LexusPermissions.Dashboard.Tenant, L("Permission:Dashboard"), MultiTenancySides.Tenant);

            //Define your own permissions here. Example:
            //myGroup.AddPermission(LexusPermissions.MyPermission1, L("Permission:MyPermission1"));
                        var lawyerPermission = myGroup.AddPermission(LawyerPermissions.Default, L("Permission:Lawyer"));
            lawyerPermission.AddChild(LawyerPermissions.Create, L("Permission:Create"));
            lawyerPermission.AddChild(LawyerPermissions.Update, L("Permission:Update"));
            lawyerPermission.AddChild(LawyerPermissions.Delete, L("Permission:Delete"));
                  var casePermission = myGroup.AddPermission(CasePermissions.Default, L("Permission:Case"));
            casePermission.AddChild(CasePermissions.Create, L("Permission:Create"));
            casePermission.AddChild(CasePermissions.Update, L("Permission:Update"));
            casePermission.AddChild(CasePermissions.Delete, L("Permission:Delete"));
                  var clientPermission = myGroup.AddPermission(ClientPermissions.Default, L("Permission:Client"));
            clientPermission.AddChild(ClientPermissions.Create, L("Permission:Create"));
            clientPermission.AddChild(ClientPermissions.Update, L("Permission:Update"));
            clientPermission.AddChild(ClientPermissions.Delete, L("Permission:Delete"));
                  var specializationPermission = myGroup.AddPermission(SpecializationPermissions.Default, L("Permission:Specialization"));
            specializationPermission.AddChild(SpecializationPermissions.Create, L("Permission:Create"));
            specializationPermission.AddChild(SpecializationPermissions.Update, L("Permission:Update"));
            specializationPermission.AddChild(SpecializationPermissions.Delete, L("Permission:Delete"));
                  var legalProcessPermission = myGroup.AddPermission(LegalProcessPermissions.Default, L("Permission:LegalProcess"));
            legalProcessPermission.AddChild(LegalProcessPermissions.Create, L("Permission:Create"));
            legalProcessPermission.AddChild(LegalProcessPermissions.Update, L("Permission:Update"));
            legalProcessPermission.AddChild(LegalProcessPermissions.Delete, L("Permission:Delete"));
                  var lawyerSpecializationPermission = myGroup.AddPermission(LawyerSpecializationPermissions.Default, L("Permission:LawyerSpecialization"));
            lawyerSpecializationPermission.AddChild(LawyerSpecializationPermissions.Create, L("Permission:Create"));
            lawyerSpecializationPermission.AddChild(LawyerSpecializationPermissions.Update, L("Permission:Update"));
            lawyerSpecializationPermission.AddChild(LawyerSpecializationPermissions.Delete, L("Permission:Delete"));
                  var proposalPermission = myGroup.AddPermission(ProposalPermissions.Default, L("Permission:Proposal"));
            proposalPermission.AddChild(ProposalPermissions.Create, L("Permission:Create"));
            proposalPermission.AddChild(ProposalPermissions.Update, L("Permission:Update"));
            proposalPermission.AddChild(ProposalPermissions.Delete, L("Permission:Delete"));
                  var propostalItemPermission = myGroup.AddPermission(PropostalItemPermissions.Default, L("Permission:PropostalItem"));
            propostalItemPermission.AddChild(PropostalItemPermissions.Create, L("Permission:Create"));
            propostalItemPermission.AddChild(PropostalItemPermissions.Update, L("Permission:Update"));
            propostalItemPermission.AddChild(PropostalItemPermissions.Delete, L("Permission:Delete"));
                  var _versaoBDPermission = myGroup.AddPermission(_versaoBDPermissions.Default, L("Permission:_versaoBD"));
            _versaoBDPermission.AddChild(_versaoBDPermissions.Create, L("Permission:Create"));
            _versaoBDPermission.AddChild(_versaoBDPermissions.Update, L("Permission:Update"));
            _versaoBDPermission.AddChild(_versaoBDPermissions.Delete, L("Permission:Delete"));
                  var advCliBairrosPermission = myGroup.AddPermission(advCliBairrosPermissions.Default, L("Permission:advCliBairros"));
            advCliBairrosPermission.AddChild(advCliBairrosPermissions.Create, L("Permission:Create"));
            advCliBairrosPermission.AddChild(advCliBairrosPermissions.Update, L("Permission:Update"));
            advCliBairrosPermission.AddChild(advCliBairrosPermissions.Delete, L("Permission:Delete"));
                  var advCliComoChegouPermission = myGroup.AddPermission(advCliComoChegouPermissions.Default, L("Permission:advCliComoChegou"));
            advCliComoChegouPermission.AddChild(advCliComoChegouPermissions.Create, L("Permission:Create"));
            advCliComoChegouPermission.AddChild(advCliComoChegouPermissions.Update, L("Permission:Update"));
            advCliComoChegouPermission.AddChild(advCliComoChegouPermissions.Delete, L("Permission:Delete"));
                  var advCliLocaisAtendidoPermission = myGroup.AddPermission(advCliLocaisAtendidoPermissions.Default, L("Permission:advCliLocaisAtendido"));
            advCliLocaisAtendidoPermission.AddChild(advCliLocaisAtendidoPermissions.Create, L("Permission:Create"));
            advCliLocaisAtendidoPermission.AddChild(advCliLocaisAtendidoPermissions.Update, L("Permission:Update"));
            advCliLocaisAtendidoPermission.AddChild(advCliLocaisAtendidoPermissions.Delete, L("Permission:Delete"));
                  var advCliLogPermission = myGroup.AddPermission(advCliLogPermissions.Default, L("Permission:advCliLog"));
            advCliLogPermission.AddChild(advCliLogPermissions.Create, L("Permission:Create"));
            advCliLogPermission.AddChild(advCliLogPermissions.Update, L("Permission:Update"));
            advCliLogPermission.AddChild(advCliLogPermissions.Delete, L("Permission:Delete"));
                  var advCliPrioridadesPermission = myGroup.AddPermission(advCliPrioridadesPermissions.Default, L("Permission:advCliPrioridades"));
            advCliPrioridadesPermission.AddChild(advCliPrioridadesPermissions.Create, L("Permission:Create"));
            advCliPrioridadesPermission.AddChild(advCliPrioridadesPermissions.Update, L("Permission:Update"));
            advCliPrioridadesPermission.AddChild(advCliPrioridadesPermissions.Delete, L("Permission:Delete"));
                  var advClientesConvertidosPermission = myGroup.AddPermission(advClientesConvertidosPermissions.Default, L("Permission:advClientesConvertidos"));
            advClientesConvertidosPermission.AddChild(advClientesConvertidosPermissions.Create, L("Permission:Create"));
            advClientesConvertidosPermission.AddChild(advClientesConvertidosPermissions.Update, L("Permission:Update"));
            advClientesConvertidosPermission.AddChild(advClientesConvertidosPermissions.Delete, L("Permission:Delete"));
                  var advClientesModelosPermission = myGroup.AddPermission(advClientesModelosPermissions.Default, L("Permission:advClientesModelos"));
            advClientesModelosPermission.AddChild(advClientesModelosPermissions.Create, L("Permission:Create"));
            advClientesModelosPermission.AddChild(advClientesModelosPermissions.Update, L("Permission:Update"));
            advClientesModelosPermission.AddChild(advClientesModelosPermissions.Delete, L("Permission:Delete"));
                  var advClientes_bkpPermission = myGroup.AddPermission(advClientes_bkpPermissions.Default, L("Permission:advClientes_bkp"));
            advClientes_bkpPermission.AddChild(advClientes_bkpPermissions.Create, L("Permission:Create"));
            advClientes_bkpPermission.AddChild(advClientes_bkpPermissions.Update, L("Permission:Update"));
            advClientes_bkpPermission.AddChild(advClientes_bkpPermissions.Delete, L("Permission:Delete"));
                  var advPautaObsPermission = myGroup.AddPermission(advPautaObsPermissions.Default, L("Permission:advPautaObs"));
            advPautaObsPermission.AddChild(advPautaObsPermissions.Create, L("Permission:Create"));
            advPautaObsPermission.AddChild(advPautaObsPermissions.Update, L("Permission:Update"));
            advPautaObsPermission.AddChild(advPautaObsPermissions.Delete, L("Permission:Delete"));
                  var advPreArquivosStatusPermission = myGroup.AddPermission(advPreArquivosStatusPermissions.Default, L("Permission:advPreArquivosStatus"));
            advPreArquivosStatusPermission.AddChild(advPreArquivosStatusPermissions.Create, L("Permission:Create"));
            advPreArquivosStatusPermission.AddChild(advPreArquivosStatusPermissions.Update, L("Permission:Update"));
            advPreArquivosStatusPermission.AddChild(advPreArquivosStatusPermissions.Delete, L("Permission:Delete"));
                  var advPreLogStatusPermission = myGroup.AddPermission(advPreLogStatusPermissions.Default, L("Permission:advPreLogStatus"));
            advPreLogStatusPermission.AddChild(advPreLogStatusPermissions.Create, L("Permission:Create"));
            advPreLogStatusPermission.AddChild(advPreLogStatusPermissions.Update, L("Permission:Update"));
            advPreLogStatusPermission.AddChild(advPreLogStatusPermissions.Delete, L("Permission:Delete"));
                  var advPreMetasPermission = myGroup.AddPermission(advPreMetasPermissions.Default, L("Permission:advPreMetas"));
            advPreMetasPermission.AddChild(advPreMetasPermissions.Create, L("Permission:Create"));
            advPreMetasPermission.AddChild(advPreMetasPermissions.Update, L("Permission:Update"));
            advPreMetasPermission.AddChild(advPreMetasPermissions.Delete, L("Permission:Delete"));
                  var advPreMotivosPerdaPermission = myGroup.AddPermission(advPreMotivosPerdaPermissions.Default, L("Permission:advPreMotivosPerda"));
            advPreMotivosPerdaPermission.AddChild(advPreMotivosPerdaPermissions.Create, L("Permission:Create"));
            advPreMotivosPerdaPermission.AddChild(advPreMotivosPerdaPermissions.Update, L("Permission:Update"));
            advPreMotivosPerdaPermission.AddChild(advPreMotivosPerdaPermissions.Delete, L("Permission:Delete"));
                  var advPreOrigensPermission = myGroup.AddPermission(advPreOrigensPermissions.Default, L("Permission:advPreOrigens"));
            advPreOrigensPermission.AddChild(advPreOrigensPermissions.Create, L("Permission:Create"));
            advPreOrigensPermission.AddChild(advPreOrigensPermissions.Update, L("Permission:Update"));
            advPreOrigensPermission.AddChild(advPreOrigensPermissions.Delete, L("Permission:Delete"));
                  var advPreProcessosCheckListsPermission = myGroup.AddPermission(advPreProcessosCheckListsPermissions.Default, L("Permission:advPreProcessosCheckLists"));
            advPreProcessosCheckListsPermission.AddChild(advPreProcessosCheckListsPermissions.Create, L("Permission:Create"));
            advPreProcessosCheckListsPermission.AddChild(advPreProcessosCheckListsPermissions.Update, L("Permission:Update"));
            advPreProcessosCheckListsPermission.AddChild(advPreProcessosCheckListsPermissions.Delete, L("Permission:Delete"));
                  var advProEscritoriosPermission = myGroup.AddPermission(advProEscritoriosPermissions.Default, L("Permission:advProEscritorios"));
            advProEscritoriosPermission.AddChild(advProEscritoriosPermissions.Create, L("Permission:Create"));
            advProEscritoriosPermission.AddChild(advProEscritoriosPermissions.Update, L("Permission:Update"));
            advProEscritoriosPermission.AddChild(advProEscritoriosPermissions.Delete, L("Permission:Delete"));
                  var advProFasesPermission = myGroup.AddPermission(advProFasesPermissions.Default, L("Permission:advProFases"));
            advProFasesPermission.AddChild(advProFasesPermissions.Create, L("Permission:Create"));
            advProFasesPermission.AddChild(advProFasesPermissions.Update, L("Permission:Update"));
            advProFasesPermission.AddChild(advProFasesPermissions.Delete, L("Permission:Delete"));
                  var advProInstanciasPermission = myGroup.AddPermission(advProInstanciasPermissions.Default, L("Permission:advProInstancias"));
            advProInstanciasPermission.AddChild(advProInstanciasPermissions.Create, L("Permission:Create"));
            advProInstanciasPermission.AddChild(advProInstanciasPermissions.Update, L("Permission:Update"));
            advProInstanciasPermission.AddChild(advProInstanciasPermissions.Delete, L("Permission:Delete"));
                  var advProOrgaosPermission = myGroup.AddPermission(advProOrgaosPermissions.Default, L("Permission:advProOrgaos"));
            advProOrgaosPermission.AddChild(advProOrgaosPermissions.Create, L("Permission:Create"));
            advProOrgaosPermission.AddChild(advProOrgaosPermissions.Update, L("Permission:Update"));
            advProOrgaosPermission.AddChild(advProOrgaosPermissions.Delete, L("Permission:Delete"));
                  var advProProbabilidadesPermission = myGroup.AddPermission(advProProbabilidadesPermissions.Default, L("Permission:advProProbabilidades"));
            advProProbabilidadesPermission.AddChild(advProProbabilidadesPermissions.Create, L("Permission:Create"));
            advProProbabilidadesPermission.AddChild(advProProbabilidadesPermissions.Update, L("Permission:Update"));
            advProProbabilidadesPermission.AddChild(advProProbabilidadesPermissions.Delete, L("Permission:Delete"));
                  var advProRelevanciasPermission = myGroup.AddPermission(advProRelevanciasPermissions.Default, L("Permission:advProRelevancias"));
            advProRelevanciasPermission.AddChild(advProRelevanciasPermissions.Create, L("Permission:Create"));
            advProRelevanciasPermission.AddChild(advProRelevanciasPermissions.Update, L("Permission:Update"));
            advProRelevanciasPermission.AddChild(advProRelevanciasPermissions.Delete, L("Permission:Delete"));
                  var advProSentencasPermission = myGroup.AddPermission(advProSentencasPermissions.Default, L("Permission:advProSentencas"));
            advProSentencasPermission.AddChild(advProSentencasPermissions.Create, L("Permission:Create"));
            advProSentencasPermission.AddChild(advProSentencasPermissions.Update, L("Permission:Update"));
            advProSentencasPermission.AddChild(advProSentencasPermissions.Delete, L("Permission:Delete"));
                  var advProStatusPermission = myGroup.AddPermission(advProStatusPermissions.Default, L("Permission:advProStatus"));
            advProStatusPermission.AddChild(advProStatusPermissions.Create, L("Permission:Create"));
            advProStatusPermission.AddChild(advProStatusPermissions.Update, L("Permission:Update"));
            advProStatusPermission.AddChild(advProStatusPermissions.Delete, L("Permission:Delete"));
                  var advProTiposPermission = myGroup.AddPermission(advProTiposPermissions.Default, L("Permission:advProTipos"));
            advProTiposPermission.AddChild(advProTiposPermissions.Create, L("Permission:Create"));
            advProTiposPermission.AddChild(advProTiposPermissions.Update, L("Permission:Update"));
            advProTiposPermission.AddChild(advProTiposPermissions.Delete, L("Permission:Delete"));
                  var advProVarasPermission = myGroup.AddPermission(advProVarasPermissions.Default, L("Permission:advProVaras"));
            advProVarasPermission.AddChild(advProVarasPermissions.Create, L("Permission:Create"));
            advProVarasPermission.AddChild(advProVarasPermissions.Update, L("Permission:Update"));
            advProVarasPermission.AddChild(advProVarasPermissions.Delete, L("Permission:Delete"));
                  var advTarefasAtualizacoesPermission = myGroup.AddPermission(advTarefasAtualizacoesPermissions.Default, L("Permission:advTarefasAtualizacoes"));
            advTarefasAtualizacoesPermission.AddChild(advTarefasAtualizacoesPermissions.Create, L("Permission:Create"));
            advTarefasAtualizacoesPermission.AddChild(advTarefasAtualizacoesPermissions.Update, L("Permission:Update"));
            advTarefasAtualizacoesPermission.AddChild(advTarefasAtualizacoesPermissions.Delete, L("Permission:Delete"));
                  var autoFTPPermission = myGroup.AddPermission(autoFTPPermissions.Default, L("Permission:autoFTP"));
            autoFTPPermission.AddChild(autoFTPPermissions.Create, L("Permission:Create"));
            autoFTPPermission.AddChild(autoFTPPermissions.Update, L("Permission:Update"));
            autoFTPPermission.AddChild(autoFTPPermissions.Delete, L("Permission:Delete"));
                  var fabConfigPermission = myGroup.AddPermission(fabConfigPermissions.Default, L("Permission:fabConfig"));
            fabConfigPermission.AddChild(fabConfigPermissions.Create, L("Permission:Create"));
            fabConfigPermission.AddChild(fabConfigPermissions.Update, L("Permission:Update"));
            fabConfigPermission.AddChild(fabConfigPermissions.Delete, L("Permission:Delete"));
                  var fabDatasEFeriadosPermission = myGroup.AddPermission(fabDatasEFeriadosPermissions.Default, L("Permission:fabDatasEFeriados"));
            fabDatasEFeriadosPermission.AddChild(fabDatasEFeriadosPermissions.Create, L("Permission:Create"));
            fabDatasEFeriadosPermission.AddChild(fabDatasEFeriadosPermissions.Update, L("Permission:Update"));
            fabDatasEFeriadosPermission.AddChild(fabDatasEFeriadosPermissions.Delete, L("Permission:Delete"));
                  var fabFormasPagamentoPermission = myGroup.AddPermission(fabFormasPagamentoPermissions.Default, L("Permission:fabFormasPagamento"));
            fabFormasPagamentoPermission.AddChild(fabFormasPagamentoPermissions.Create, L("Permission:Create"));
            fabFormasPagamentoPermission.AddChild(fabFormasPagamentoPermissions.Update, L("Permission:Update"));
            fabFormasPagamentoPermission.AddChild(fabFormasPagamentoPermissions.Delete, L("Permission:Delete"));
                  var fabFormasRecebimentoPermission = myGroup.AddPermission(fabFormasRecebimentoPermissions.Default, L("Permission:fabFormasRecebimento"));
            fabFormasRecebimentoPermission.AddChild(fabFormasRecebimentoPermissions.Create, L("Permission:Create"));
            fabFormasRecebimentoPermission.AddChild(fabFormasRecebimentoPermissions.Update, L("Permission:Update"));
            fabFormasRecebimentoPermission.AddChild(fabFormasRecebimentoPermissions.Delete, L("Permission:Delete"));
                  var fabMotivosAproveitamentoPermission = myGroup.AddPermission(fabMotivosAproveitamentoPermissions.Default, L("Permission:fabMotivosAproveitamento"));
            fabMotivosAproveitamentoPermission.AddChild(fabMotivosAproveitamentoPermissions.Create, L("Permission:Create"));
            fabMotivosAproveitamentoPermission.AddChild(fabMotivosAproveitamentoPermissions.Update, L("Permission:Update"));
            fabMotivosAproveitamentoPermission.AddChild(fabMotivosAproveitamentoPermissions.Delete, L("Permission:Delete"));
                  var fabMotivosPerdaPermission = myGroup.AddPermission(fabMotivosPerdaPermissions.Default, L("Permission:fabMotivosPerda"));
            fabMotivosPerdaPermission.AddChild(fabMotivosPerdaPermissions.Create, L("Permission:Create"));
            fabMotivosPerdaPermission.AddChild(fabMotivosPerdaPermissions.Update, L("Permission:Update"));
            fabMotivosPerdaPermission.AddChild(fabMotivosPerdaPermissions.Delete, L("Permission:Delete"));
                  var fabRegioesPermission = myGroup.AddPermission(fabRegioesPermissions.Default, L("Permission:fabRegioes"));
            fabRegioesPermission.AddChild(fabRegioesPermissions.Create, L("Permission:Create"));
            fabRegioesPermission.AddChild(fabRegioesPermissions.Update, L("Permission:Update"));
            fabRegioesPermission.AddChild(fabRegioesPermissions.Delete, L("Permission:Delete"));
                  var fdtDevsPermission = myGroup.AddPermission(fdtDevsPermissions.Default, L("Permission:fdtDevs"));
            fdtDevsPermission.AddChild(fdtDevsPermissions.Create, L("Permission:Create"));
            fdtDevsPermission.AddChild(fdtDevsPermissions.Update, L("Permission:Update"));
            fdtDevsPermission.AddChild(fdtDevsPermissions.Delete, L("Permission:Delete"));
                  var finCentrosResultadoPermission = myGroup.AddPermission(finCentrosResultadoPermissions.Default, L("Permission:finCentrosResultado"));
            finCentrosResultadoPermission.AddChild(finCentrosResultadoPermissions.Create, L("Permission:Create"));
            finCentrosResultadoPermission.AddChild(finCentrosResultadoPermissions.Update, L("Permission:Update"));
            finCentrosResultadoPermission.AddChild(finCentrosResultadoPermissions.Delete, L("Permission:Delete"));
                  var finContasClientesPermission = myGroup.AddPermission(finContasClientesPermissions.Default, L("Permission:finContasClientes"));
            finContasClientesPermission.AddChild(finContasClientesPermissions.Create, L("Permission:Create"));
            finContasClientesPermission.AddChild(finContasClientesPermissions.Update, L("Permission:Update"));
            finContasClientesPermission.AddChild(finContasClientesPermissions.Delete, L("Permission:Delete"));
                  var finLancamentos_BKPPermission = myGroup.AddPermission(finLancamentos_BKPPermissions.Default, L("Permission:finLancamentos_BKP"));
            finLancamentos_BKPPermission.AddChild(finLancamentos_BKPPermissions.Create, L("Permission:Create"));
            finLancamentos_BKPPermission.AddChild(finLancamentos_BKPPermissions.Update, L("Permission:Update"));
            finLancamentos_BKPPermission.AddChild(finLancamentos_BKPPermissions.Delete, L("Permission:Delete"));
                  var finPlanoContasDetPermission = myGroup.AddPermission(finPlanoContasDetPermissions.Default, L("Permission:finPlanoContasDet"));
            finPlanoContasDetPermission.AddChild(finPlanoContasDetPermissions.Create, L("Permission:Create"));
            finPlanoContasDetPermission.AddChild(finPlanoContasDetPermissions.Update, L("Permission:Update"));
            finPlanoContasDetPermission.AddChild(finPlanoContasDetPermissions.Delete, L("Permission:Delete"));
                  var finProcuracoesRPVPermission = myGroup.AddPermission(finProcuracoesRPVPermissions.Default, L("Permission:finProcuracoesRPV"));
            finProcuracoesRPVPermission.AddChild(finProcuracoesRPVPermissions.Create, L("Permission:Create"));
            finProcuracoesRPVPermission.AddChild(finProcuracoesRPVPermissions.Update, L("Permission:Update"));
            finProcuracoesRPVPermission.AddChild(finProcuracoesRPVPermissions.Delete, L("Permission:Delete"));
                  var finRateiosPermission = myGroup.AddPermission(finRateiosPermissions.Default, L("Permission:finRateios"));
            finRateiosPermission.AddChild(finRateiosPermissions.Create, L("Permission:Create"));
            finRateiosPermission.AddChild(finRateiosPermissions.Update, L("Permission:Update"));
            finRateiosPermission.AddChild(finRateiosPermissions.Delete, L("Permission:Delete"));
                  var finRateiosPadraoPermission = myGroup.AddPermission(finRateiosPadraoPermissions.Default, L("Permission:finRateiosPadrao"));
            finRateiosPadraoPermission.AddChild(finRateiosPadraoPermissions.Create, L("Permission:Create"));
            finRateiosPadraoPermission.AddChild(finRateiosPadraoPermissions.Update, L("Permission:Update"));
            finRateiosPadraoPermission.AddChild(finRateiosPadraoPermissions.Delete, L("Permission:Delete"));
                  var finRecibosPermission = myGroup.AddPermission(finRecibosPermissions.Default, L("Permission:finRecibos"));
            finRecibosPermission.AddChild(finRecibosPermissions.Create, L("Permission:Create"));
            finRecibosPermission.AddChild(finRecibosPermissions.Update, L("Permission:Update"));
            finRecibosPermission.AddChild(finRecibosPermissions.Delete, L("Permission:Delete"));
                  var finUnidadesPermission = myGroup.AddPermission(finUnidadesPermissions.Default, L("Permission:finUnidades"));
            finUnidadesPermission.AddChild(finUnidadesPermissions.Create, L("Permission:Create"));
            finUnidadesPermission.AddChild(finUnidadesPermissions.Update, L("Permission:Update"));
            finUnidadesPermission.AddChild(finUnidadesPermissions.Delete, L("Permission:Delete"));
                  var flwConfigPermission = myGroup.AddPermission(flwConfigPermissions.Default, L("Permission:flwConfig"));
            flwConfigPermission.AddChild(flwConfigPermissions.Create, L("Permission:Create"));
            flwConfigPermission.AddChild(flwConfigPermissions.Update, L("Permission:Update"));
            flwConfigPermission.AddChild(flwConfigPermissions.Delete, L("Permission:Delete"));
                  var advAgeTiposCompromissosPermission = myGroup.AddPermission(advAgeTiposCompromissosPermissions.Default, L("Permission:advAgeTiposCompromissos"));
            advAgeTiposCompromissosPermission.AddChild(advAgeTiposCompromissosPermissions.Create, L("Permission:Create"));
            advAgeTiposCompromissosPermission.AddChild(advAgeTiposCompromissosPermissions.Update, L("Permission:Update"));
            advAgeTiposCompromissosPermission.AddChild(advAgeTiposCompromissosPermissions.Delete, L("Permission:Delete"));
                  var advAgeTiposTarefasPermission = myGroup.AddPermission(advAgeTiposTarefasPermissions.Default, L("Permission:advAgeTiposTarefas"));
            advAgeTiposTarefasPermission.AddChild(advAgeTiposTarefasPermissions.Create, L("Permission:Create"));
            advAgeTiposTarefasPermission.AddChild(advAgeTiposTarefasPermissions.Update, L("Permission:Update"));
            advAgeTiposTarefasPermission.AddChild(advAgeTiposTarefasPermissions.Delete, L("Permission:Delete"));
                  var advCliCargosPermission = myGroup.AddPermission(advCliCargosPermissions.Default, L("Permission:advCliCargos"));
            advCliCargosPermission.AddChild(advCliCargosPermissions.Create, L("Permission:Create"));
            advCliCargosPermission.AddChild(advCliCargosPermissions.Update, L("Permission:Update"));
            advCliCargosPermission.AddChild(advCliCargosPermissions.Delete, L("Permission:Delete"));
                  var advCliGruposPermission = myGroup.AddPermission(advCliGruposPermissions.Default, L("Permission:advCliGrupos"));
            advCliGruposPermission.AddChild(advCliGruposPermissions.Create, L("Permission:Create"));
            advCliGruposPermission.AddChild(advCliGruposPermissions.Update, L("Permission:Update"));
            advCliGruposPermission.AddChild(advCliGruposPermissions.Delete, L("Permission:Delete"));
                  var advCliSituacoesPermission = myGroup.AddPermission(advCliSituacoesPermissions.Default, L("Permission:advCliSituacoes"));
            advCliSituacoesPermission.AddChild(advCliSituacoesPermissions.Create, L("Permission:Create"));
            advCliSituacoesPermission.AddChild(advCliSituacoesPermissions.Update, L("Permission:Update"));
            advCliSituacoesPermission.AddChild(advCliSituacoesPermissions.Delete, L("Permission:Delete"));
                  var advCliTiposArquivosPermission = myGroup.AddPermission(advCliTiposArquivosPermissions.Default, L("Permission:advCliTiposArquivos"));
            advCliTiposArquivosPermission.AddChild(advCliTiposArquivosPermissions.Create, L("Permission:Create"));
            advCliTiposArquivosPermission.AddChild(advCliTiposArquivosPermissions.Update, L("Permission:Update"));
            advCliTiposArquivosPermission.AddChild(advCliTiposArquivosPermissions.Delete, L("Permission:Delete"));
                  var advCliTiposHistoricosPermission = myGroup.AddPermission(advCliTiposHistoricosPermissions.Default, L("Permission:advCliTiposHistoricos"));
            advCliTiposHistoricosPermission.AddChild(advCliTiposHistoricosPermissions.Create, L("Permission:Create"));
            advCliTiposHistoricosPermission.AddChild(advCliTiposHistoricosPermissions.Update, L("Permission:Update"));
            advCliTiposHistoricosPermission.AddChild(advCliTiposHistoricosPermissions.Delete, L("Permission:Delete"));
                  var advClientesINSSStatusPermission = myGroup.AddPermission(advClientesINSSStatusPermissions.Default, L("Permission:advClientesINSSStatus"));
            advClientesINSSStatusPermission.AddChild(advClientesINSSStatusPermissions.Create, L("Permission:Create"));
            advClientesINSSStatusPermission.AddChild(advClientesINSSStatusPermissions.Update, L("Permission:Update"));
            advClientesINSSStatusPermission.AddChild(advClientesINSSStatusPermissions.Delete, L("Permission:Delete"));
                  var advFornecedoresPermission = myGroup.AddPermission(advFornecedoresPermissions.Default, L("Permission:advFornecedores"));
            advFornecedoresPermission.AddChild(advFornecedoresPermissions.Create, L("Permission:Create"));
            advFornecedoresPermission.AddChild(advFornecedoresPermissions.Update, L("Permission:Update"));
            advFornecedoresPermission.AddChild(advFornecedoresPermissions.Delete, L("Permission:Delete"));
                  var advPostosINSSPermission = myGroup.AddPermission(advPostosINSSPermissions.Default, L("Permission:advPostosINSS"));
            advPostosINSSPermission.AddChild(advPostosINSSPermissions.Create, L("Permission:Create"));
            advPostosINSSPermission.AddChild(advPostosINSSPermissions.Update, L("Permission:Update"));
            advPostosINSSPermission.AddChild(advPostosINSSPermissions.Delete, L("Permission:Delete"));
                  var advPreCheckListsGruposPermission = myGroup.AddPermission(advPreCheckListsGruposPermissions.Default, L("Permission:advPreCheckListsGrupos"));
            advPreCheckListsGruposPermission.AddChild(advPreCheckListsGruposPermissions.Create, L("Permission:Create"));
            advPreCheckListsGruposPermission.AddChild(advPreCheckListsGruposPermissions.Update, L("Permission:Update"));
            advPreCheckListsGruposPermission.AddChild(advPreCheckListsGruposPermissions.Delete, L("Permission:Delete"));
                  var advPreStatusTiposPermission = myGroup.AddPermission(advPreStatusTiposPermissions.Default, L("Permission:advPreStatusTipos"));
            advPreStatusTiposPermission.AddChild(advPreStatusTiposPermissions.Create, L("Permission:Create"));
            advPreStatusTiposPermission.AddChild(advPreStatusTiposPermissions.Update, L("Permission:Update"));
            advPreStatusTiposPermission.AddChild(advPreStatusTiposPermissions.Delete, L("Permission:Delete"));
                  var advProMeritosPermission = myGroup.AddPermission(advProMeritosPermissions.Default, L("Permission:advProMeritos"));
            advProMeritosPermission.AddChild(advProMeritosPermissions.Create, L("Permission:Create"));
            advProMeritosPermission.AddChild(advProMeritosPermissions.Update, L("Permission:Update"));
            advProMeritosPermission.AddChild(advProMeritosPermissions.Delete, L("Permission:Delete"));
                  var advProNaturezasPermission = myGroup.AddPermission(advProNaturezasPermissions.Default, L("Permission:advProNaturezas"));
            advProNaturezasPermission.AddChild(advProNaturezasPermissions.Create, L("Permission:Create"));
            advProNaturezasPermission.AddChild(advProNaturezasPermissions.Update, L("Permission:Update"));
            advProNaturezasPermission.AddChild(advProNaturezasPermissions.Delete, L("Permission:Delete"));
                  var advVerTiposPermission = myGroup.AddPermission(advVerTiposPermissions.Default, L("Permission:advVerTipos"));
            advVerTiposPermission.AddChild(advVerTiposPermissions.Create, L("Permission:Create"));
            advVerTiposPermission.AddChild(advVerTiposPermissions.Update, L("Permission:Update"));
            advVerTiposPermission.AddChild(advVerTiposPermissions.Delete, L("Permission:Delete"));
                  var fabCondicoesPagamentoPermission = myGroup.AddPermission(fabCondicoesPagamentoPermissions.Default, L("Permission:fabCondicoesPagamento"));
            fabCondicoesPagamentoPermission.AddChild(fabCondicoesPagamentoPermissions.Create, L("Permission:Create"));
            fabCondicoesPagamentoPermission.AddChild(fabCondicoesPagamentoPermissions.Update, L("Permission:Update"));
            fabCondicoesPagamentoPermission.AddChild(fabCondicoesPagamentoPermissions.Delete, L("Permission:Delete"));
                  var fabHistoricoTiposPermission = myGroup.AddPermission(fabHistoricoTiposPermissions.Default, L("Permission:fabHistoricoTipos"));
            fabHistoricoTiposPermission.AddChild(fabHistoricoTiposPermissions.Create, L("Permission:Create"));
            fabHistoricoTiposPermission.AddChild(fabHistoricoTiposPermissions.Update, L("Permission:Update"));
            fabHistoricoTiposPermission.AddChild(fabHistoricoTiposPermissions.Delete, L("Permission:Delete"));
                  var fabPaisesPermission = myGroup.AddPermission(fabPaisesPermissions.Default, L("Permission:fabPaises"));
            fabPaisesPermission.AddChild(fabPaisesPermissions.Create, L("Permission:Create"));
            fabPaisesPermission.AddChild(fabPaisesPermissions.Update, L("Permission:Update"));
            fabPaisesPermission.AddChild(fabPaisesPermissions.Delete, L("Permission:Delete"));
                  var fabPermissoesTiposPermission = myGroup.AddPermission(fabPermissoesTiposPermissions.Default, L("Permission:fabPermissoesTipos"));
            fabPermissoesTiposPermission.AddChild(fabPermissoesTiposPermissions.Create, L("Permission:Create"));
            fabPermissoesTiposPermission.AddChild(fabPermissoesTiposPermissions.Update, L("Permission:Update"));
            fabPermissoesTiposPermission.AddChild(fabPermissoesTiposPermissions.Delete, L("Permission:Delete"));
                  var finAreasPermission = myGroup.AddPermission(finAreasPermissions.Default, L("Permission:finAreas"));
            finAreasPermission.AddChild(finAreasPermissions.Create, L("Permission:Create"));
            finAreasPermission.AddChild(finAreasPermissions.Update, L("Permission:Update"));
            finAreasPermission.AddChild(finAreasPermissions.Delete, L("Permission:Delete"));
                  var finCentrosCustoPermission = myGroup.AddPermission(finCentrosCustoPermissions.Default, L("Permission:finCentrosCusto"));
            finCentrosCustoPermission.AddChild(finCentrosCustoPermissions.Create, L("Permission:Create"));
            finCentrosCustoPermission.AddChild(finCentrosCustoPermissions.Update, L("Permission:Update"));
            finCentrosCustoPermission.AddChild(finCentrosCustoPermissions.Delete, L("Permission:Delete"));
                  var finContasPermission = myGroup.AddPermission(finContasPermissions.Default, L("Permission:finContas"));
            finContasPermission.AddChild(finContasPermissions.Create, L("Permission:Create"));
            finContasPermission.AddChild(finContasPermissions.Update, L("Permission:Update"));
            finContasPermission.AddChild(finContasPermissions.Delete, L("Permission:Delete"));
                  var finGruposDREPermission = myGroup.AddPermission(finGruposDREPermissions.Default, L("Permission:finGruposDRE"));
            finGruposDREPermission.AddChild(finGruposDREPermissions.Create, L("Permission:Create"));
            finGruposDREPermission.AddChild(finGruposDREPermissions.Update, L("Permission:Update"));
            finGruposDREPermission.AddChild(finGruposDREPermissions.Delete, L("Permission:Delete"));
                  var flwAcoesPermission = myGroup.AddPermission(flwAcoesPermissions.Default, L("Permission:flwAcoes"));
            flwAcoesPermission.AddChild(flwAcoesPermissions.Create, L("Permission:Create"));
            flwAcoesPermission.AddChild(flwAcoesPermissions.Update, L("Permission:Update"));
            flwAcoesPermission.AddChild(flwAcoesPermissions.Delete, L("Permission:Delete"));
                  var logAcoesPermission = myGroup.AddPermission(logAcoesPermissions.Default, L("Permission:logAcoes"));
            logAcoesPermission.AddChild(logAcoesPermissions.Create, L("Permission:Create"));
            logAcoesPermission.AddChild(logAcoesPermissions.Update, L("Permission:Update"));
            logAcoesPermission.AddChild(logAcoesPermissions.Delete, L("Permission:Delete"));
                  var opoSituacoesPermission = myGroup.AddPermission(opoSituacoesPermissions.Default, L("Permission:opoSituacoes"));
            opoSituacoesPermission.AddChild(opoSituacoesPermissions.Create, L("Permission:Create"));
            opoSituacoesPermission.AddChild(opoSituacoesPermissions.Update, L("Permission:Update"));
            opoSituacoesPermission.AddChild(opoSituacoesPermissions.Delete, L("Permission:Delete"));
                  var opoTiposPermission = myGroup.AddPermission(opoTiposPermissions.Default, L("Permission:opoTipos"));
            opoTiposPermission.AddChild(opoTiposPermissions.Create, L("Permission:Create"));
            opoTiposPermission.AddChild(opoTiposPermissions.Update, L("Permission:Update"));
            opoTiposPermission.AddChild(opoTiposPermissions.Delete, L("Permission:Delete"));
                  var usuAreasPermission = myGroup.AddPermission(usuAreasPermissions.Default, L("Permission:usuAreas"));
            usuAreasPermission.AddChild(usuAreasPermissions.Create, L("Permission:Create"));
            usuAreasPermission.AddChild(usuAreasPermissions.Update, L("Permission:Update"));
            usuAreasPermission.AddChild(usuAreasPermissions.Delete, L("Permission:Delete"));
                  var advClientesPermission = myGroup.AddPermission(advClientesPermissions.Default, L("Permission:advClientes"));
            advClientesPermission.AddChild(advClientesPermissions.Create, L("Permission:Create"));
            advClientesPermission.AddChild(advClientesPermissions.Update, L("Permission:Update"));
            advClientesPermission.AddChild(advClientesPermissions.Delete, L("Permission:Delete"));
                  var advClientesArquivosPermission = myGroup.AddPermission(advClientesArquivosPermissions.Default, L("Permission:advClientesArquivos"));
            advClientesArquivosPermission.AddChild(advClientesArquivosPermissions.Create, L("Permission:Create"));
            advClientesArquivosPermission.AddChild(advClientesArquivosPermissions.Update, L("Permission:Update"));
            advClientesArquivosPermission.AddChild(advClientesArquivosPermissions.Delete, L("Permission:Delete"));
                  var advClientesAtualizacoesPermission = myGroup.AddPermission(advClientesAtualizacoesPermissions.Default, L("Permission:advClientesAtualizacoes"));
            advClientesAtualizacoesPermission.AddChild(advClientesAtualizacoesPermissions.Create, L("Permission:Create"));
            advClientesAtualizacoesPermission.AddChild(advClientesAtualizacoesPermissions.Update, L("Permission:Update"));
            advClientesAtualizacoesPermission.AddChild(advClientesAtualizacoesPermissions.Delete, L("Permission:Delete"));
                  var advClientesChecklistPermission = myGroup.AddPermission(advClientesChecklistPermissions.Default, L("Permission:advClientesChecklist"));
            advClientesChecklistPermission.AddChild(advClientesChecklistPermissions.Create, L("Permission:Create"));
            advClientesChecklistPermission.AddChild(advClientesChecklistPermissions.Update, L("Permission:Update"));
            advClientesChecklistPermission.AddChild(advClientesChecklistPermissions.Delete, L("Permission:Delete"));
                  var advClientesINSSPermission = myGroup.AddPermission(advClientesINSSPermissions.Default, L("Permission:advClientesINSS"));
            advClientesINSSPermission.AddChild(advClientesINSSPermissions.Create, L("Permission:Create"));
            advClientesINSSPermission.AddChild(advClientesINSSPermissions.Update, L("Permission:Update"));
            advClientesINSSPermission.AddChild(advClientesINSSPermissions.Delete, L("Permission:Delete"));
                  var advPreCheckListsPermission = myGroup.AddPermission(advPreCheckListsPermissions.Default, L("Permission:advPreCheckLists"));
            advPreCheckListsPermission.AddChild(advPreCheckListsPermissions.Create, L("Permission:Create"));
            advPreCheckListsPermission.AddChild(advPreCheckListsPermissions.Update, L("Permission:Update"));
            advPreCheckListsPermission.AddChild(advPreCheckListsPermissions.Delete, L("Permission:Delete"));
                  var advPreStatusPermission = myGroup.AddPermission(advPreStatusPermissions.Default, L("Permission:advPreStatus"));
            advPreStatusPermission.AddChild(advPreStatusPermissions.Create, L("Permission:Create"));
            advPreStatusPermission.AddChild(advPreStatusPermissions.Update, L("Permission:Update"));
            advPreStatusPermission.AddChild(advPreStatusPermissions.Delete, L("Permission:Delete"));
                  var advProcessosPermission = myGroup.AddPermission(advProcessosPermissions.Default, L("Permission:advProcessos"));
            advProcessosPermission.AddChild(advProcessosPermissions.Create, L("Permission:Create"));
            advProcessosPermission.AddChild(advProcessosPermissions.Update, L("Permission:Update"));
            advProcessosPermission.AddChild(advProcessosPermissions.Delete, L("Permission:Delete"));
                  var advProcessosClientesPermission = myGroup.AddPermission(advProcessosClientesPermissions.Default, L("Permission:advProcessosClientes"));
            advProcessosClientesPermission.AddChild(advProcessosClientesPermissions.Create, L("Permission:Create"));
            advProcessosClientesPermission.AddChild(advProcessosClientesPermissions.Update, L("Permission:Update"));
            advProcessosClientesPermission.AddChild(advProcessosClientesPermissions.Delete, L("Permission:Delete"));
                  var advProcessosHonorariosPermission = myGroup.AddPermission(advProcessosHonorariosPermissions.Default, L("Permission:advProcessosHonorarios"));
            advProcessosHonorariosPermission.AddChild(advProcessosHonorariosPermissions.Create, L("Permission:Create"));
            advProcessosHonorariosPermission.AddChild(advProcessosHonorariosPermissions.Update, L("Permission:Update"));
            advProcessosHonorariosPermission.AddChild(advProcessosHonorariosPermissions.Delete, L("Permission:Delete"));
                  var advProcessosMeritosPermission = myGroup.AddPermission(advProcessosMeritosPermissions.Default, L("Permission:advProcessosMeritos"));
            advProcessosMeritosPermission.AddChild(advProcessosMeritosPermissions.Create, L("Permission:Create"));
            advProcessosMeritosPermission.AddChild(advProcessosMeritosPermissions.Update, L("Permission:Update"));
            advProcessosMeritosPermission.AddChild(advProcessosMeritosPermissions.Delete, L("Permission:Delete"));
                  var fabEstadosPermission = myGroup.AddPermission(fabEstadosPermissions.Default, L("Permission:fabEstados"));
            fabEstadosPermission.AddChild(fabEstadosPermissions.Create, L("Permission:Create"));
            fabEstadosPermission.AddChild(fabEstadosPermissions.Update, L("Permission:Update"));
            fabEstadosPermission.AddChild(fabEstadosPermissions.Delete, L("Permission:Delete"));
                  var fabPermissoesPermission = myGroup.AddPermission(fabPermissoesPermissions.Default, L("Permission:fabPermissoes"));
            fabPermissoesPermission.AddChild(fabPermissoesPermissions.Create, L("Permission:Create"));
            fabPermissoesPermission.AddChild(fabPermissoesPermissions.Update, L("Permission:Update"));
            fabPermissoesPermission.AddChild(fabPermissoesPermissions.Delete, L("Permission:Delete"));
                  var finExtratoPermission = myGroup.AddPermission(finExtratoPermissions.Default, L("Permission:finExtrato"));
            finExtratoPermission.AddChild(finExtratoPermissions.Create, L("Permission:Create"));
            finExtratoPermission.AddChild(finExtratoPermissions.Update, L("Permission:Update"));
            finExtratoPermission.AddChild(finExtratoPermissions.Delete, L("Permission:Delete"));
                  var finPlanoContasGruposPermission = myGroup.AddPermission(finPlanoContasGruposPermissions.Default, L("Permission:finPlanoContasGrupos"));
            finPlanoContasGruposPermission.AddChild(finPlanoContasGruposPermissions.Create, L("Permission:Create"));
            finPlanoContasGruposPermission.AddChild(finPlanoContasGruposPermissions.Update, L("Permission:Update"));
            finPlanoContasGruposPermission.AddChild(finPlanoContasGruposPermissions.Delete, L("Permission:Delete"));
                  var flwConfigExcecoesPermission = myGroup.AddPermission(flwConfigExcecoesPermissions.Default, L("Permission:flwConfigExcecoes"));
            flwConfigExcecoesPermission.AddChild(flwConfigExcecoesPermissions.Create, L("Permission:Create"));
            flwConfigExcecoesPermission.AddChild(flwConfigExcecoesPermissions.Update, L("Permission:Update"));
            flwConfigExcecoesPermission.AddChild(flwConfigExcecoesPermissions.Delete, L("Permission:Delete"));
                  var flwGradeHorariosPermission = myGroup.AddPermission(flwGradeHorariosPermissions.Default, L("Permission:flwGradeHorarios"));
            flwGradeHorariosPermission.AddChild(flwGradeHorariosPermissions.Create, L("Permission:Create"));
            flwGradeHorariosPermission.AddChild(flwGradeHorariosPermissions.Update, L("Permission:Update"));
            flwGradeHorariosPermission.AddChild(flwGradeHorariosPermissions.Delete, L("Permission:Delete"));
                  var logCamposPermission = myGroup.AddPermission(logCamposPermissions.Default, L("Permission:logCampos"));
            logCamposPermission.AddChild(logCamposPermissions.Create, L("Permission:Create"));
            logCamposPermission.AddChild(logCamposPermissions.Update, L("Permission:Update"));
            logCamposPermission.AddChild(logCamposPermissions.Delete, L("Permission:Delete"));
                  var usuCargosPermission = myGroup.AddPermission(usuCargosPermissions.Default, L("Permission:usuCargos"));
            usuCargosPermission.AddChild(usuCargosPermissions.Create, L("Permission:Create"));
            usuCargosPermission.AddChild(usuCargosPermissions.Update, L("Permission:Update"));
            usuCargosPermission.AddChild(usuCargosPermissions.Delete, L("Permission:Delete"));
                  var advClientesHistoricosPermission = myGroup.AddPermission(advClientesHistoricosPermissions.Default, L("Permission:advClientesHistoricos"));
            advClientesHistoricosPermission.AddChild(advClientesHistoricosPermissions.Create, L("Permission:Create"));
            advClientesHistoricosPermission.AddChild(advClientesHistoricosPermissions.Update, L("Permission:Update"));
            advClientesHistoricosPermission.AddChild(advClientesHistoricosPermissions.Delete, L("Permission:Delete"));
                  var advCompromissosPermission = myGroup.AddPermission(advCompromissosPermissions.Default, L("Permission:advCompromissos"));
            advCompromissosPermission.AddChild(advCompromissosPermissions.Create, L("Permission:Create"));
            advCompromissosPermission.AddChild(advCompromissosPermissions.Update, L("Permission:Update"));
            advCompromissosPermission.AddChild(advCompromissosPermissions.Delete, L("Permission:Delete"));
                  var advProcessosAlteracoesPermission = myGroup.AddPermission(advProcessosAlteracoesPermissions.Default, L("Permission:advProcessosAlteracoes"));
            advProcessosAlteracoesPermission.AddChild(advProcessosAlteracoesPermissions.Create, L("Permission:Create"));
            advProcessosAlteracoesPermission.AddChild(advProcessosAlteracoesPermissions.Update, L("Permission:Update"));
            advProcessosAlteracoesPermission.AddChild(advProcessosAlteracoesPermissions.Delete, L("Permission:Delete"));
                  var advProcessosDadosHerdeirosPermission = myGroup.AddPermission(advProcessosDadosHerdeirosPermissions.Default, L("Permission:advProcessosDadosHerdeiros"));
            advProcessosDadosHerdeirosPermission.AddChild(advProcessosDadosHerdeirosPermissions.Create, L("Permission:Create"));
            advProcessosDadosHerdeirosPermission.AddChild(advProcessosDadosHerdeirosPermissions.Update, L("Permission:Update"));
            advProcessosDadosHerdeirosPermission.AddChild(advProcessosDadosHerdeirosPermissions.Delete, L("Permission:Delete"));
                  var advProfissionaisPermission = myGroup.AddPermission(advProfissionaisPermissions.Default, L("Permission:advProfissionais"));
            advProfissionaisPermission.AddChild(advProfissionaisPermissions.Create, L("Permission:Create"));
            advProfissionaisPermission.AddChild(advProfissionaisPermissions.Update, L("Permission:Update"));
            advProfissionaisPermission.AddChild(advProfissionaisPermissions.Delete, L("Permission:Delete"));
                  var advProfissionaisEstadosPermission = myGroup.AddPermission(advProfissionaisEstadosPermissions.Default, L("Permission:advProfissionaisEstados"));
            advProfissionaisEstadosPermission.AddChild(advProfissionaisEstadosPermissions.Create, L("Permission:Create"));
            advProfissionaisEstadosPermission.AddChild(advProfissionaisEstadosPermissions.Update, L("Permission:Update"));
            advProfissionaisEstadosPermission.AddChild(advProfissionaisEstadosPermissions.Delete, L("Permission:Delete"));
                  var advProfissionaisNaturezasPermission = myGroup.AddPermission(advProfissionaisNaturezasPermissions.Default, L("Permission:advProfissionaisNaturezas"));
            advProfissionaisNaturezasPermission.AddChild(advProfissionaisNaturezasPermissions.Create, L("Permission:Create"));
            advProfissionaisNaturezasPermission.AddChild(advProfissionaisNaturezasPermissions.Update, L("Permission:Update"));
            advProfissionaisNaturezasPermission.AddChild(advProfissionaisNaturezasPermissions.Delete, L("Permission:Delete"));
                  var advRevisaoDocumentosPermission = myGroup.AddPermission(advRevisaoDocumentosPermissions.Default, L("Permission:advRevisaoDocumentos"));
            advRevisaoDocumentosPermission.AddChild(advRevisaoDocumentosPermissions.Create, L("Permission:Create"));
            advRevisaoDocumentosPermission.AddChild(advRevisaoDocumentosPermissions.Update, L("Permission:Update"));
            advRevisaoDocumentosPermission.AddChild(advRevisaoDocumentosPermissions.Delete, L("Permission:Delete"));
                  var advTarefasPermission = myGroup.AddPermission(advTarefasPermissions.Default, L("Permission:advTarefas"));
            advTarefasPermission.AddChild(advTarefasPermissions.Create, L("Permission:Create"));
            advTarefasPermission.AddChild(advTarefasPermissions.Update, L("Permission:Update"));
            advTarefasPermission.AddChild(advTarefasPermissions.Delete, L("Permission:Delete"));
                  var advVerbasPermission = myGroup.AddPermission(advVerbasPermissions.Default, L("Permission:advVerbas"));
            advVerbasPermission.AddChild(advVerbasPermissions.Create, L("Permission:Create"));
            advVerbasPermission.AddChild(advVerbasPermissions.Update, L("Permission:Update"));
            advVerbasPermission.AddChild(advVerbasPermissions.Delete, L("Permission:Delete"));
                  var fabCidadesPermission = myGroup.AddPermission(fabCidadesPermissions.Default, L("Permission:fabCidades"));
            fabCidadesPermission.AddChild(fabCidadesPermissions.Create, L("Permission:Create"));
            fabCidadesPermission.AddChild(fabCidadesPermissions.Update, L("Permission:Update"));
            fabCidadesPermission.AddChild(fabCidadesPermissions.Delete, L("Permission:Delete"));
                  var fabLembretesPermission = myGroup.AddPermission(fabLembretesPermissions.Default, L("Permission:fabLembretes"));
            fabLembretesPermission.AddChild(fabLembretesPermissions.Create, L("Permission:Create"));
            fabLembretesPermission.AddChild(fabLembretesPermissions.Update, L("Permission:Update"));
            fabLembretesPermission.AddChild(fabLembretesPermissions.Delete, L("Permission:Delete"));
                  var finPlanoContasPermission = myGroup.AddPermission(finPlanoContasPermissions.Default, L("Permission:finPlanoContas"));
            finPlanoContasPermission.AddChild(finPlanoContasPermissions.Create, L("Permission:Create"));
            finPlanoContasPermission.AddChild(finPlanoContasPermissions.Update, L("Permission:Update"));
            finPlanoContasPermission.AddChild(finPlanoContasPermissions.Delete, L("Permission:Delete"));
                  var opoOportunidadesPermission = myGroup.AddPermission(opoOportunidadesPermissions.Default, L("Permission:opoOportunidades"));
            opoOportunidadesPermission.AddChild(opoOportunidadesPermissions.Create, L("Permission:Create"));
            opoOportunidadesPermission.AddChild(opoOportunidadesPermissions.Update, L("Permission:Update"));
            opoOportunidadesPermission.AddChild(opoOportunidadesPermissions.Delete, L("Permission:Delete"));
                  var opoOrcamentosPermission = myGroup.AddPermission(opoOrcamentosPermissions.Default, L("Permission:opoOrcamentos"));
            opoOrcamentosPermission.AddChild(opoOrcamentosPermissions.Create, L("Permission:Create"));
            opoOrcamentosPermission.AddChild(opoOrcamentosPermissions.Update, L("Permission:Update"));
            opoOrcamentosPermission.AddChild(opoOrcamentosPermissions.Delete, L("Permission:Delete"));
                  var usuAcessosPermission = myGroup.AddPermission(usuAcessosPermissions.Default, L("Permission:usuAcessos"));
            usuAcessosPermission.AddChild(usuAcessosPermissions.Create, L("Permission:Create"));
            usuAcessosPermission.AddChild(usuAcessosPermissions.Update, L("Permission:Update"));
            usuAcessosPermission.AddChild(usuAcessosPermissions.Delete, L("Permission:Delete"));
                  var usuDistanciasPermission = myGroup.AddPermission(usuDistanciasPermissions.Default, L("Permission:usuDistancias"));
            usuDistanciasPermission.AddChild(usuDistanciasPermissions.Create, L("Permission:Create"));
            usuDistanciasPermission.AddChild(usuDistanciasPermissions.Update, L("Permission:Update"));
            usuDistanciasPermission.AddChild(usuDistanciasPermissions.Delete, L("Permission:Delete"));
                  var finLancamentosPermission = myGroup.AddPermission(finLancamentosPermissions.Default, L("Permission:finLancamentos"));
            finLancamentosPermission.AddChild(finLancamentosPermissions.Create, L("Permission:Create"));
            finLancamentosPermission.AddChild(finLancamentosPermissions.Update, L("Permission:Update"));
            finLancamentosPermission.AddChild(finLancamentosPermissions.Delete, L("Permission:Delete"));
                  var finPrestacaoContasPermission = myGroup.AddPermission(finPrestacaoContasPermissions.Default, L("Permission:finPrestacaoContas"));
            finPrestacaoContasPermission.AddChild(finPrestacaoContasPermissions.Create, L("Permission:Create"));
            finPrestacaoContasPermission.AddChild(finPrestacaoContasPermissions.Update, L("Permission:Update"));
            finPrestacaoContasPermission.AddChild(finPrestacaoContasPermissions.Delete, L("Permission:Delete"));
                  var flwFollowsPermission = myGroup.AddPermission(flwFollowsPermissions.Default, L("Permission:flwFollows"));
            flwFollowsPermission.AddChild(flwFollowsPermissions.Create, L("Permission:Create"));
            flwFollowsPermission.AddChild(flwFollowsPermissions.Update, L("Permission:Update"));
            flwFollowsPermission.AddChild(flwFollowsPermissions.Delete, L("Permission:Delete"));
      // <ZenCode-PermissionDefinition-Marker>
        }

        private static LocalizableString L(string name)
        {
            return LocalizableString.Create<LexusResource>(name);
        }
    }
}