// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Gdpr;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Volo.Abp.Gdpr;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IGdprRequestAppService), typeof(GdprRequestClientProxy))]
public partial class GdprRequestClientProxy : ClientProxyBase<IGdprRequestAppService>, IGdprRequestAppService
{
    public virtual async Task PrepareUserDataAsync()
    {
        await RequestAsync(nameof(PrepareUserDataAsync));
    }

    public virtual async Task<DownloadTokenResultDto> GetDownloadTokenAsync(Guid id)
    {
        return await RequestAsync<DownloadTokenResultDto>(nameof(GetDownloadTokenAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetUserDataAsync(Guid requestId, string token)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetUserDataAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), requestId },
            { typeof(string), token }
        });
    }

    public virtual async Task<bool> IsNewRequestAllowedAsync()
    {
        return await RequestAsync<bool>(nameof(IsNewRequestAllowedAsync));
    }

    public virtual async Task<PagedResultDto<GdprRequestDto>> GetListAsync(GdprRequestInput input)
    {
        return await RequestAsync<PagedResultDto<GdprRequestDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GdprRequestInput), input }
        });
    }

    public virtual async Task DeleteUserDataAsync()
    {
        await RequestAsync(nameof(DeleteUserDataAsync));
    }
}
