// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;
using Volo.CmsKit.Public.PageFeedbacks;

// ReSharper disable once CheckNamespace
namespace Volo.CmsKit.Public.PageFeedbacks;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPageFeedbackPublicAppService), typeof(PageFeedbackPublicClientProxy))]
public partial class PageFeedbackPublicClientProxy : ClientProxyBase<IPageFeedbackPublicAppService>, IPageFeedbackPublicAppService
{
    public virtual async Task<PageFeedbackDto> CreateAsync(CreatePageFeedbackInput input)
    {
        return await RequestAsync<PageFeedbackDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreatePageFeedbackInput), input }
        });
    }

    public virtual async Task<PageFeedbackDto> InitializeUserNoteAsync(InitializeUserNoteInput input)
    {
        return await RequestAsync<PageFeedbackDto>(nameof(InitializeUserNoteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(InitializeUserNoteInput), input }
        });
    }

    public virtual async Task<PageFeedbackDto> ChangeIsUsefulAsync(ChangeIsUsefulInput input)
    {
        return await RequestAsync<PageFeedbackDto>(nameof(ChangeIsUsefulAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ChangeIsUsefulInput), input }
        });
    }
}
