/**
 * AI Import Parser
 * Converts AI extracted entities to ZenCode EntityData format
 */

import type { AIExtractionResult, AIExtractedEntity, AIExtractedEnum } from '../gemini/types';
import type { EntityData, EntityField, FieldType } from '../../types';
import { pluralize } from '../../utils/pluralize';

/**
 * Convert AI extracted field type to ZenCode field type
 */
function mapFieldType(aiType: string): FieldType {
    const typeMap: Record<string, FieldType> = {
        'string': 'string',
        'int': 'int',
        'long': 'long',
        'double': 'double',
        'decimal': 'decimal',
        'bool': 'bool',
        'datetime': 'datetime',
        'guid': 'guid',
        'enum': 'enum',
    };
    return typeMap[aiType.toLowerCase()] || 'string';
}

/**
 * Fields that are auto-generated by ABP base classes and should NOT be included
 * These are inherited from FullAuditedAggregateRoot, AuditedEntity, etc.
 */
const ABP_AUTO_FIELDS = new Set([
    'id',
    'tenantid',
    'createdat',
    'updatedat',
    'creationtime',
    'creatorid',
    'lastmodificationtime',
    'lastmodifierid',
    'isdeleted',
    'deleterid',
    'deletiontime',
    'concurrencystamp',
    'extraproperties',
]);

/**
 * Check if a field is auto-generated by ABP
 */
function isAbpAutoField(fieldName: string): boolean {
    return ABP_AUTO_FIELDS.has(fieldName.toLowerCase());
}

/**
 * Convert AI extracted entity to ZenCode EntityData
 */
export function convertAIEntityToEntityData(
    aiEntity: AIExtractedEntity,
    _enums: AIExtractedEnum[]
): EntityData {
    // Filter out ABP auto-generated fields
    const filteredFields = aiEntity.fields.filter(f => !isAbpAutoField(f.name));

    const fields: EntityField[] = filteredFields.map((field, index) => {
        const entityField: EntityField = {
            id: `field_${Date.now()}_${index}`,
            name: field.name,
            type: mapFieldType(field.type),
            isRequired: field.isRequired ?? false,
            isNullable: !field.isRequired,
            isFilterable: true,
            isTextArea: field.type === 'string' && (field.maxLength ?? 0) > 500,
            showInGrid: true,
            showInForm: true,
            label: field.label || field.name,
            placeholder: field.placeholder,
        };

        // Add validation
        if (field.maxLength) {
            entityField.maxLength = field.maxLength;
        }

        // Note: Enum handling will need EntityField type to be extended
        // For now, we skip enum-specific properties

        return entityField;
    });

    return {
        name: aiEntity.name,
        pluralName: aiEntity.pluralName || pluralize(aiEntity.name),
        tableName: aiEntity.pluralName || pluralize(aiEntity.name),
        namespace: 'App', // Will be set by user in settings
        baseClass: 'FullAuditedAggregateRoot',
        isMaster: true,
        fields,
    };
}

/**
 * Result of parsing AI extraction to canvas format
 */
export interface ParsedAIImport {
    entities: EntityData[];
    relationships: {
        sourceEntityName: string;
        targetEntityName: string;
        type: 'one-to-many' | 'many-to-many';
        fkFieldName?: string;
        description?: string;
    }[];
}

/**
 * Detect relationships from FK fields in entities
 * Fields ending in "Id" that match another entity name are FK fields
 */
function detectFKRelationships(entities: EntityData[]): ParsedAIImport['relationships'] {
    const entityNames = new Set(entities.map(e => e.name.toLowerCase()));
    const relationships: ParsedAIImport['relationships'] = [];

    for (const entity of entities) {
        for (const field of entity.fields) {
            // Check if field is an FK (ends with Id and type is guid)
            if (field.name.endsWith('Id') && field.type === 'guid') {
                // Extract potential entity name from FK field (e.g., "SchoolId" -> "School")
                const potentialTargetName = field.name.slice(0, -2);

                // Check if there's an entity with that name
                if (entityNames.has(potentialTargetName.toLowerCase())) {
                    // Find actual entity name with correct casing
                    const targetEntity = entities.find(
                        e => e.name.toLowerCase() === potentialTargetName.toLowerCase()
                    );

                    if (targetEntity && targetEntity.name !== entity.name) {
                        relationships.push({
                            sourceEntityName: entity.name,
                            targetEntityName: targetEntity.name,
                            type: 'one-to-many',
                            fkFieldName: field.name,
                            description: `${entity.name} belongs to ${targetEntity.name}`,
                        });
                    }
                }
            }
        }
    }

    return relationships;
}

/**
 * Parse full AI extraction result to canvas-ready format
 */
export function parseAIExtractionToCanvas(result: AIExtractionResult): ParsedAIImport {
    const entities = result.entities.map(e => convertAIEntityToEntityData(e, result.enums));

    // Combine AI-provided relationships with FK-detected relationships
    const aiRelationships = result.relationships.map(rel => ({
        sourceEntityName: rel.sourceEntity,
        targetEntityName: rel.targetEntity,
        type: rel.type,
        description: rel.description,
    }));

    const fkRelationships = detectFKRelationships(entities);

    // Merge and dedupe relationships
    const relationshipMap = new Map<string, ParsedAIImport['relationships'][0]>();

    // Add FK-detected first (they have fkFieldName)
    for (const rel of fkRelationships) {
        const key = `${rel.sourceEntityName}->${rel.targetEntityName}`;
        relationshipMap.set(key, rel);
    }

    // Override with AI-provided (they may have better type info like N:N)
    for (const rel of aiRelationships) {
        const key = `${rel.sourceEntityName}->${rel.targetEntityName}`;
        relationshipMap.set(key, rel);
    }

    return {
        entities,
        relationships: Array.from(relationshipMap.values())
    };
}

/**
 * Calculate grid positions for imported entities
 */
export function calculateEntityPositions(count: number): { x: number; y: number }[] {
    const positions: { x: number; y: number }[] = [];
    const cols = Math.ceil(Math.sqrt(count));
    const spacing = { x: 280, y: 220 };
    const offset = { x: 100, y: 100 };

    for (let i = 0; i < count; i++) {
        const col = i % cols;
        const row = Math.floor(i / cols);
        positions.push({
            x: offset.x + col * spacing.x,
            y: offset.y + row * spacing.y,
        });
    }

    return positions;
}
