// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;
using Volo.CmsKit.Admin.Faqs;

// ReSharper disable once CheckNamespace
namespace Volo.CmsKit.Admin.Faqs;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IFaqQuestionAdminAppService), typeof(FaqQuestionAdminClientProxy))]
public partial class FaqQuestionAdminClientProxy : ClientProxyBase<IFaqQuestionAdminAppService>, IFaqQuestionAdminAppService
{
    public virtual async Task<FaqQuestionDto> GetAsync(Guid id)
    {
        return await RequestAsync<FaqQuestionDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<FaqQuestionDto>> GetListAsync(FaqQuestionListFilterDto input)
    {
        return await RequestAsync<PagedResultDto<FaqQuestionDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(FaqQuestionListFilterDto), input }
        });
    }

    public virtual async Task<FaqQuestionDto> CreateAsync(CreateFaqQuestionDto input)
    {
        return await RequestAsync<FaqQuestionDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreateFaqQuestionDto), input }
        });
    }

    public virtual async Task<FaqQuestionDto> UpdateAsync(Guid id, UpdateFaqQuestionDto input)
    {
        return await RequestAsync<FaqQuestionDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(UpdateFaqQuestionDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
