// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;
using Volo.CmsKit.Admin.Faqs;

// ReSharper disable once CheckNamespace
namespace Volo.CmsKit.Admin.Faqs;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IFaqSectionAdminAppService), typeof(FaqSectionAdminClientProxy))]
public partial class FaqSectionAdminClientProxy : ClientProxyBase<IFaqSectionAdminAppService>, IFaqSectionAdminAppService
{
    public virtual async Task<FaqSectionDto> GetAsync(Guid id)
    {
        return await RequestAsync<FaqSectionDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<FaqSectionWithQuestionCountDto>> GetListAsync(FaqSectionListFilterDto input)
    {
        return await RequestAsync<PagedResultDto<FaqSectionWithQuestionCountDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(FaqSectionListFilterDto), input }
        });
    }

    public virtual async Task<FaqSectionDto> CreateAsync(CreateFaqSectionDto input)
    {
        return await RequestAsync<FaqSectionDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreateFaqSectionDto), input }
        });
    }

    public virtual async Task<FaqSectionDto> UpdateAsync(Guid id, UpdateFaqSectionDto input)
    {
        return await RequestAsync<FaqSectionDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(UpdateFaqSectionDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<Dictionary<String, FaqGroupInfoDto>> GetGroupsAsync()
    {
        return await RequestAsync<Dictionary<String, FaqGroupInfoDto>>(nameof(GetGroupsAsync));
    }
}
